# Generated by Django 3.2.4 on 2021-08-11 22:50

from django.db import migrations, models
import multiselectfield.db.fields
import workshops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'Basic'), (6, 'Intermediate'), (7, 'Advance')], max_length=5, null=True)),
                ('frequency', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13, null=True)),
                ('cover_page', models.ImageField(blank=True, upload_to='poster', validators=[workshops.models.validate_img_file])),
                ('temary', models.ImageField(blank=True, upload_to='temary', validators=[workshops.models.validate_pdf_file])),
            ],
        ),
    ]
