# Generated by Django 3.2.4 on 2021-09-15 00:14

from django.db import migrations, models
import multiselectfield.db.fields
import workshops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('level', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advance')], max_length=5)),
                ('frequency', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cover', models.ImageField(blank=True, upload_to='poster', validators=[workshops.models.validate_img_file])),
                ('temary', models.FileField(blank=True, upload_to='temary', validators=[workshops.models.validate_pdf_file])),
            ],
        ),
    ]
