# Generated by Django 3.2.4 on 2021-08-11 22:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='frequency',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'Basic'), (6, 'Intermediate'), (7, 'Advance')], default=None, max_length=5, null=True),
        ),
    ]
