# Generated by Django 3.2.4 on 2021-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20210914_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
