# Generated by Django 3.2.4 on 2021-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_workshops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
